const fs = require('fs');

const files = ['index.html', 'js/app.js', 'js/dados.js', 'js/mapa.js', 'js/escolas.js'];
const c = '\uFFFD';

const replacements = {
    // Structural
    [`(!str) return '${c}';`]: `(!str) return '-';`,
    [`>GBZ ${c} v1.0<`]: `>GBZ - v1.0<`,
    [`>GBZ ${c} v1.0<`]: `>GBZ - v1.0<`,
    [`>${c}</span>`]: `>-</span>`,
    [`'${c}'`]: `'-'`,
    [`""`]: `"****"`,
    [`${c} Limpar Filtros`]: `✗ Limpar Filtros`,
    
    // Words
    [`ARTICULA${c}${c}O`]: `ARTICULAÇÃO`,
    [`D${c}GITOS`]: `DÍGITOS`,
    [`CONTE${c}DO`]: `CONTEÚDO`,
    [`usu${c}rio`]: `usuário`,
    [`usu${c}rios`]: `usuários`,
    [`Usu${c}rio`]: `Usuário`,
    [`Distribui${c}${c}o`]: `Distribuição`,
    [`Se${c}${c}o`]: `Seção`,
    [`SE${c}${c}O`]: `SEÇÃO`,
    [`c${c}digo`]: `código`,
    [`C${c}digo`]: `Código`,
    [`n${c}mero`]: `número`,
    [`N${c}mero`]: `Número`,
    [`N${c}MEROS`]: `NÚMEROS`,
    [`An${c}lise`]: `Análise`,
    [`Relat${c}rio`]: `Relatório`,
    [`Padr${c}o`]: `Padrão`,
    [`munic${c}pio`]: `município`,
    [`Munic${c}pio`]: `Município`,
    [`munic${c}pios`]: `municípios`,
    [`AUTORIZA${c}${c}O`]: `AUTORIZAÇÃO`,
    [`Autoriza${c}${c}es`]: `Autorizações`,
    [`Autoriza${c}${c}o`]: `Autorização`,
    [`Conv${c}nio`]: `Convênio`,
    [`Coopera${c}${c}o`]: `Cooperação`,
    [`Marca${c}${c}o`]: `Marcação`,
    [`Pagina${c}${c}o`]: `Paginação`,
    [`Formul${c}rio`]: `Formulário`,
    [`FORMUL${c}RIO`]: `FORMULÁRIO`,
    [`N${c} do`]: `Nº do`,
    [`N${c} Processo`]: `Nº Processo`,
    [`N${c} de`]: `Nº de`,
    [`Endereço e N${c}`]: `Endereço e Nº`,
    [`atualiza${c}${c}o`]: `atualização`,
    [`Descri${c}${c}o`]: `Descrição`,
    [`Observa${c}${c}es`]: `Observações`,
    [`OBSERVA${c}${c}ES`]: `OBSERVAÇÕES`,
    [`Observa${c}${c}o`]: `Observação`,
    [`Anota${c}${c}o`]: `Anotação`,
    [`Anota${c}${c}es`]: `Anotações`,
    [`hist${c}rico`]: `histórico`,
    [`Bot${c}o`]: `Botão`,
    [`Bot${c}es`]: `Botões`,
    [`AUDIT${c}RIO`]: `AUDITÓRIO`,
    [`P${c}TIO`]: `PÁTIO`,
    [`REFEIT${c}RIO`]: `REFEITÓRIO`,
    [`Acess${c}vel`]: `Acessível`,
    [`Of${c}cio`]: `Ofício`,
    [`licita${c}${c}o`]: `licitação`,
    [`An${c}sio`]: `Anísio`,
    [`m${c}`]: `m²`,
    [`M${c}veis`]: `Móveis`,
    [`arm${c}rios`]: `armários`,
    [`A${c}${c}o`]: `Ação`,
    [`A${c}${c}es`]: `Ações`,
    [`Cr${c}t`]: `Crít`,
    [`Diferen${c}a`]: `Diferença`,
    [` j${c} `]: ` já `,
    [`ser${c}o`]: `serão`,
    [`Aten${c}${c}o`]: `Atenção`,
    [`apagar${c}`]: `apagará`,
    [`n${c}o`]: `não`,
    [`N${c}o`]: `Não`,
    [`N${c}O`]: `NÃO`,
    [`EDI${c}${c}O`]: `EDIÇÃO`,
    [`edi${c}${c}o`]: `edição`,
    [`N${c}vel`]: `Nível`,
    [`N${c}VEL`]: `NÍVEL`,
    [`${c}ltimo`]: `Último`,
    [`${c}LTIMO`]: `ÚLTIMO`,
    [`Cabe${c}alho`]: `Cabeçalho`,
    [`cabe${c}alho`]: `cabeçalho`,
    [`IDENTIFICA${c}${c}O`]: `IDENTIFICAÇÃO`,
    [`Identifica${c}${c}o`]: `Identificação`,
    [`Ind${c}gena`]: `Indígena`,
    [`GEST${c}O`]: `GESTÃO`,
    [`Gest${c}O`]: `Gestão`, // oops wait Gestão
    [`Gest${c}o`]: `Gestão`,
    [`DIRE${c}${c}O`]: `DIREÇÃO`,
    [`respons${c}vel`]: `responsável`,
    [`ENDERE${c}O`]: `ENDEREÇO`,
    [`Pr${c}ximo`]: `Próximo`,
    [`pra${c}a`]: `praça`,
    [`altera${c}${c}es`]: `alterações`,
    [`Altera${c}${c}es`]: `Alteraçōes`,
    [`informa${c}${c}es`]: `informações`,
    [`depura${c}${c}o`]: `depuração`,
    [`dinamicame`]: `dinamicamente`,
    [`SINT${c}TICO`]: `SINTÉTICO`,
    [`Sint${c}tico`]: `Sintético`,
    [`T${c}cnica`]: `Técnica`,
    [`Fundamenta${c}${c}o`]: `Fundamentação`,
    [`FUN${c}${c}O`]: `FUNÇÃO`,
    [`M${c}dulo`]: `Módulo`,
    [`autentica${c}${c}o`]: `autenticação`,
    [`CONCLU${c}DO`]: `CONCLUÍDO`,
    [`AQUISI${c}${c}O`]: `AQUISIÇÃO`,
    [`CONSTRU${c}${c}O`]: `CONSTRUÇÃO`,
    [`AMPLIA${c}${c}O`]: `AMPLIAÇÃO`,
    [`MOBILI${c}RIO`]: `MOBILIÁRIO`,
    [`${c}nico`]: `único`,
    [`inv${c}lida`]: `inválida`,
    [`est${c}`]: `está`,
    [`UTILIT${c}RIOS`]: `UTILITÁRIOS`,
    [`Rond${c}nia`]: `Rondônia`,
    [`Calibra${c}${c}o`]: `Calibração`,
    [`Arigol${c}ndia`]: `Arigolândia`,
    [`Aponi${c}`]: `Aponiã`,
    [`Concei${c}${c}o`]: `Conceição`,
    [`Tri${c}ngulo`]: `Triângulo`,
    [`geogr${c}fica`]: `geográfica`,
    [`igarap${c}`]: `igarapé`,
    [`apon${c}`]: `aponã`,
    [`gra${c}as`]: `graças`,
    [`guimar${c}es`]: `guimarães`,
    [`arag${c}o`]: `aragão`,
    [`s${c}o`]: `são`,
    [`S${c}o`]: `São`,
    [`tri${c}ngulo`]: `triângulo`,
    [`uni${c}o`]: `união`,
    [`b${c}rbara`]: `bárbara`,
    [`sebasti${c}o`]: `sebastião`,
    [`esperan${c}a`]: `esperança`,
    [`${c}rea`]: `área`,
    [`urup${c}`]: `urupá`,
    [`cana${c}`]: `canaã`,
    [`geogr${c}ficas`]: `geográficas`,
    [`mai${c}sculo`]: `maiúsculo`,
    [`mai${c}sculas`]: `maiúsculas`,
    [`Crist${c}v${c}o`]: `Cristóvão`,
    [`Igarap${c}`]: `Igarapé`,
    [`Paran${c}`]: `Paraná`,
    [`Guajar${c}-Mirim`]: `Guajará-Mirim`,
    [`Espig${c}o`]: `Espigão`,
    [`Mamor${c}`]: `Mamoré`,
    [`Guapor${c}`]: `Guaporé`,
    [`M${c}dici`]: `Médici`,
    [`Para${c}so`]: `Paraíso`,
    [`Brasil${c}ndia`]: `Brasilândia`,
    [`Teixeir${c}polis`]: `Teixeirópolis`,
    [`Itapu${c}`]: `Itapuã`,
    [`Cacaul${c}ndia`]: `Cacaulândia`,
    [`Uni${c}o`]: `União`,
    [`espa${c}os`]: `espaços`,
    [`ap${c}strofos`]: `apóstrofos`,
    [`can${c}nica`]: `canônica`,
    [`inst${c}ncia`]: `instância`,
    [`renderiza${c}${c}o`]: `renderização`,
    [`dispers${c}o`]: `dispersão`,
    [`${c}urea`]: `áurea`,
    [`${c}ngulo`]: `ângulo`,
    [`M${c}ximo`]: `Máximo`,
    [`n${c}o-urbana`]: `não-urbana`,
    [`exclu${c}da`]: `excluída`,
    
    // Some left overs
    [`Altera${c}es`]: `Alterações`,
    [`MUNIC${c}PIO`]: `MUNICÍPIO`,
    [`Localiza${c}o`]: `Localização`
};

files.forEach(file => {
    if (fs.existsSync(file)) {
        let content = fs.readFileSync(file, 'utf8');
        let original = content;

        for (const [key, value] of Object.entries(replacements)) {
            // Because some replacements might replace others, we just do it sequentially
            content = content.split(key).join(value);
        }

        if (content !== original) {
            fs.writeFileSync(file, content, 'utf8');
            console.log(`Fixed ${file}`);
        } else {
            console.log(`No changes for ${file}`);
        }
    }
});
