$lines = Get-Content -Path .\js\escolas.js -Encoding UTF8
$lines[2] = "// SEDUC - FormulÃ¡rio Individualizado de Escola (PÃ¡gina & Modal)"
$lines[19] = "    if (typeof toast === 'function') toast('Escola nÃ£o encontrada para ediÃ§Ã£o', 'error');"
$lines[28] = "// SEDUC - FormulÃ¡rio Individualizado de Escola (PÃ¡gina & Modal)"
$lines[45] = "    if (typeof toast === 'function') toast('Escola nÃ£o encontrada para ediÃ§Ã£o', 'error');"
$lines[59] = "  if (titulo) titulo.innerHTML = 'âœ¨ Nova Escola';"
$lines[63] = "  if (btn) btn.textContent = 'ðŸ’¾ Salvar Nova Escola';"
$lines[94] = "  // Atualizar modal tambÃ©m para sincronia"
$lines[98] = "  if (titulo) titulo.innerHTML = 'âœï¸ Editar Cadastro da Escola';"
$lines[102] = "  if (btn) btn.textContent = 'ðŸ’¾ Salvar AlteraÃ§Ãµes';"
$lines[158] = "    if (btn) { btn.disabled = false; btn.textContent = 'ðŸ’¾ Salvar AlteraÃ§Ãµes'; }"
$lines[163] = "// SEDUC - MÃ³dulo de Escolas (ADM ONLY) - v3.0"
$lines[255] = "// ---- INICIALIZAR PÃGINA ----"
$lines[272] = "  "Alta Floresta d'Oeste", "Alto Alegre dos Parecis", "Alto ParaÃ­so", "Alvorada d'Oeste", "Ariquemes", "
$lines[273] = "  "Buritis", "Cabixi", "CacaulÃ¢ndia", "Cacoal", "Campo Novo de RondÃ´nia", "Candeias do Jamari", "
$lines[275] = "  "Cujubim", "EspigÃ£o d'Oeste", "Governador Jorge Teixeira", "GuajarÃ¡-Mirim", "ItapuÃ£ do Oeste", "
$lines[276] = "  "Jaru", "Ji-ParanÃ¡", "Machadinho d'Oeste", "Ministro Andreazza", "Mirante da Serra", "Monte Negro", "
$lines[277] = "  "Nova BrasilÃ¢ndia d'Oeste", "Nova MamorÃ©", "Nova UniÃ£o", "Novo Horizonte do Oeste", "Ouro Preto do Oeste", "
$lines[278] = "  "Parecis", "Pimenta Bueno", "Pimenteiras do Oeste", "Porto Velho", "Presidente MÃ©dici", "
$lines[279] = "  "Primavera de RondÃ´nia", "Rio Crespo", "Rolim de Moura", "Santa Luzia d'Oeste", "SÃ£o Felipe d'Oeste", "
$lines[280] = "  "SÃ£o Francisco do GuaporÃ©", "SÃ£o Miguel do GuaporÃ©", "Seringueiras", "TeixeirÃ³polis", "Theobroma", "
$lines[281] = "  "UrupÃ¡", "Vale do Anari", "Vale do ParaÃ­so", "Vilhena""
$lines[297] = "  if (val(0).toUpperCase() === 'MUNICÃPIO/DISTRITO' || val(0).toUpperCase() === 'MUNICÃPIO') return null;"
$lines[332] = "  if (val(0).toUpperCase() === 'MUNICÃPIO/DISTRITO' || val(0).toUpperCase() === 'MUNICÃPIO') return null;"
$lines[364] = "  if (badgeEl) badgeEl.textContent = 'â³ Carregando...';"
$lines[373] = "    if (badgeEl) badgeEl.textContent = 'â³ Carregando Estadual...';"
$lines[395] = "      if (badgeEl) badgeEl.textContent = 'â³ Carregando Municipal (' + (batchStart+batchMuns.length) + '/' + MUNICIPIOS_RO.length + ')...';"
$lines[494] = "    if (badgeEl) badgeEl.textContent = 'âŒ Erro ao carregar escolas';"
$lines[525] = "  if (badgeEscolas) badgeEscolas.textContent = 'ðŸ« ' + totalEscolas.toLocaleString('pt-BR') + ' Escolas';"
$lines[526] = "  if (badgeAlunos)  badgeAlunos.textContent  = 'ðŸŽ“ ' + totalAlunos.toLocaleString('pt-BR') + ' Alunos';"
$lines[527] = "  if (badgeSalas)   badgeSalas.textContent   = 'ðŸ“š ' + totalSalas.toLocaleString('pt-BR') + ' Salas';"
$lines[598] = "    if (badgeEscolas) badgeEscolas.textContent = 'ðŸ« Escolas';"
$lines[599] = "    if (badgeAlunos)  badgeAlunos.textContent  = 'ðŸŽ“ Alunos';"
$lines[600] = "    if (badgeSalas)   badgeSalas.textContent   = 'ðŸ“š Salas';"
$lines[621] = "    if (badgeEscolas) badgeEscolas.textContent = 'ðŸ« Escolas';"
$lines[636] = "      'IndÃ­gena': { bg: 'rgba(245,158,11,0.15)', color: '#fbbf24', border: 'rgba(245,158,11,0.3)' },"
$lines[668] = "          '<button onclick="abrirFormEscolaByInepOrId(\'' + idKey + '\')" title="Editar Dados da Escola" style="background:linear-gradient(135deg,#8b5cf6,#7c3aed);border:none;border-radius:6px;color:#ffffff;padding:6px 14px;cursor:pointer;font-size:13px;font-weight:700;display:inline-flex;align-items:center;gap:4px;box-shadow:0 2px 8px rgba(139,92,246,0.3);">âœï¸ Editar</button>' +"
$lines[675] = "// ---- PAGINAÃ‡ÃƒO ----"
$lines[707] = "  let btns = '<button class="page-btn" ' + (_escolasPaginaAtual === 1 ? 'disabled' : '') + ' onclick="navegarEscolas(' + (_escolasPaginaAtual - 1) + ')">â—€</button>';"
$lines[712] = "  btns += '<button class="page-btn" ' + (_escolasPaginaAtual === totPag ? 'disabled' : '') + ' onclick="navegarEscolas(' + (_escolasPaginaAtual + 1) + ')">â–¶</button>';"
$lines[726] = "    toast('Escola nÃ£o encontrada para ediÃ§Ã£o', 'error');"
$lines[768] = "  if (titulo) titulo.innerHTML = 'âœï¸ Editar Dados da Escola';"
$lines[774] = "  if (btn) btn.textContent = 'ðŸ’¾ Salvar AlteraÃ§Ãµes';"
$lines[849] = "    if (btn) { btn.disabled = false; btn.textContent = 'ðŸ’¾ Salvar AlteraÃ§Ãµes'; }"
$lines[854] = "  if (!confirm('Tem certeza que deseja excluir esta escola? Esta aÃ§Ã£o nÃ£o pode ser desfeita.')) return;"
$lines[861] = "    toast('Escola excluÃ­da com sucesso!', 'success');"
$lines[913] = "    if (typeof toast === 'function') toast('Escola nÃ£o encontrada para ediÃ§Ã£o', 'error');"
$lines[945] = "    h += '<h2>RelatÃ³rio de Escolas - SEDUC/RO (CAM)</h2>';"
$lines[956] = "    h += '<th class="num">NÂº</th>';"
$lines[957] = "    h += '<th>CompetÃªncia</th>';"
$lines[959] = "    h += '<th>MunicÃ­pio</th>';"
$lines[961] = "    h += '<th class="center">LocalizaÃ§Ã£o</th>';"
$lines[963] = "    h += '<th class="right">MatrÃ­culas</th>';"
$lines[1012] = "    alert('Erro ao gerar relatÃ³rio: ' + err.message);"
$lines | Set-Content -Path .\js\escolas.js -Encoding UTF8
