$script = @"
`$lines = Get-Content -Path .\js\escolas.js -Encoding UTF8
`$lines[2] = "// SEDUC - Formulário Individualizado de Escola (Página & Modal)"
`$lines[19] = "    if (typeof toast === 'function') toast('Escola não encontrada para edição', 'error');"
`$lines[28] = "// SEDUC - Formulário Individualizado de Escola (Página & Modal)"
`$lines[45] = "    if (typeof toast === 'function') toast('Escola não encontrada para edição', 'error');"
`$lines[59] = "  if (titulo) titulo.innerHTML = '✨ Nova Escola';"
`$lines[63] = "  if (btn) btn.textContent = '💾 Salvar Nova Escola';"
`$lines[94] = "  // Atualizar modal também para sincronia"
`$lines[98] = "  if (titulo) titulo.innerHTML = '✏️ Editar Cadastro da Escola';"
`$lines[102] = "  if (btn) btn.textContent = '💾 Salvar Alterações';"
`$lines[158] = "    if (btn) { btn.disabled = false; btn.textContent = '💾 Salvar Alterações'; }"
`$lines[163] = "// SEDUC - Módulo de Escolas (ADM ONLY) - v3.0"
`$lines[255] = "// ---- INICIALIZAR PÁGINA ----"
`$lines[272] = "  `"Alta Floresta d'Oeste`", `"Alto Alegre dos Parecis`", `"Alto Paraíso`", `"Alvorada d'Oeste`", `"Ariquemes`", "
`$lines[273] = "  `"Buritis`", `"Cabixi`", `"Cacaulândia`", `"Cacoal`", `"Campo Novo de Rondônia`", `"Candeias do Jamari`", "
`$lines[275] = "  `"Cujubim`", `"Espigão d'Oeste`", `"Governador Jorge Teixeira`", `"Guajará-Mirim`", `"Itapuã do Oeste`", "
`$lines[276] = "  `"Jaru`", `"Ji-Paraná`", `"Machadinho d'Oeste`", `"Ministro Andreazza`", `"Mirante da Serra`", `"Monte Negro`", "
`$lines[277] = "  `"Nova Brasilândia d'Oeste`", `"Nova Mamoré`", `"Nova União`", `"Novo Horizonte do Oeste`", `"Ouro Preto do Oeste`", "
`$lines[278] = "  `"Parecis`", `"Pimenta Bueno`", `"Pimenteiras do Oeste`", `"Porto Velho`", `"Presidente Médici`", "
`$lines[279] = "  `"Primavera de Rondônia`", `"Rio Crespo`", `"Rolim de Moura`", `"Santa Luzia d'Oeste`", `"São Felipe d'Oeste`", "
`$lines[280] = "  `"São Francisco do Guaporé`", `"São Miguel do Guaporé`", `"Seringueiras`", `"Teixeirópolis`", `"Theobroma`", "
`$lines[281] = "  `"Urupá`", `"Vale do Anari`", `"Vale do Paraíso`", `"Vilhena`""
`$lines[297] = "  if (val(0).toUpperCase() === 'MUNICÍPIO/DISTRITO' || val(0).toUpperCase() === 'MUNICÍPIO') return null;"
`$lines[332] = "  if (val(0).toUpperCase() === 'MUNICÍPIO/DISTRITO' || val(0).toUpperCase() === 'MUNICÍPIO') return null;"
`$lines[364] = "  if (badgeEl) badgeEl.textContent = '⏳ Carregando...';"
`$lines[373] = "    if (badgeEl) badgeEl.textContent = '⏳ Carregando Estadual...';"
`$lines[395] = "      if (badgeEl) badgeEl.textContent = '⏳ Carregando Municipal (' + (batchStart+batchMuns.length) + '/' + MUNICIPIOS_RO.length + ')...';"
`$lines[494] = "    if (badgeEl) badgeEl.textContent = '❌ Erro ao carregar escolas';"
`$lines[525] = "  if (badgeEscolas) badgeEscolas.textContent = '🏫 ' + totalEscolas.toLocaleString('pt-BR') + ' Escolas';"
`$lines[526] = "  if (badgeAlunos)  badgeAlunos.textContent  = '🎓 ' + totalAlunos.toLocaleString('pt-BR') + ' Alunos';"
`$lines[527] = "  if (badgeSalas)   badgeSalas.textContent   = '📚 ' + totalSalas.toLocaleString('pt-BR') + ' Salas';"
`$lines[598] = "    if (badgeEscolas) badgeEscolas.textContent = '🏫 Escolas';"
`$lines[599] = "    if (badgeAlunos)  badgeAlunos.textContent  = '🎓 Alunos';"
`$lines[600] = "    if (badgeSalas)   badgeSalas.textContent   = '📚 Salas';"
`$lines[621] = "    if (badgeEscolas) badgeEscolas.textContent = '🏫 Escolas';"
`$lines[636] = "      'Indígena': { bg: 'rgba(245,158,11,0.15)', color: '#fbbf24', border: 'rgba(245,158,11,0.3)' },"
`$lines[668] = "          '<button onclick=`"abrirFormEscolaByInepOrId(\'' + idKey + '\')`" title=`"Editar Dados da Escola`" style=`"background:linear-gradient(135deg,#8b5cf6,#7c3aed);border:none;border-radius:6px;color:#ffffff;padding:6px 14px;cursor:pointer;font-size:13px;font-weight:700;display:inline-flex;align-items:center;gap:4px;box-shadow:0 2px 8px rgba(139,92,246,0.3);`">✏️ Editar</button>' +"
`$lines[675] = "// ---- PAGINAÇÃO ----"
`$lines[707] = "  let btns = '<button class=`"page-btn`" ' + (_escolasPaginaAtual === 1 ? 'disabled' : '') + ' onclick=`"navegarEscolas(' + (_escolasPaginaAtual - 1) + ')`">◀</button>';"
`$lines[712] = "  btns += '<button class=`"page-btn`" ' + (_escolasPaginaAtual === totPag ? 'disabled' : '') + ' onclick=`"navegarEscolas(' + (_escolasPaginaAtual + 1) + ')`">▶</button>';"
`$lines[726] = "    toast('Escola não encontrada para edição', 'error');"
`$lines[768] = "  if (titulo) titulo.innerHTML = '✏️ Editar Dados da Escola';"
`$lines[774] = "  if (btn) btn.textContent = '💾 Salvar Alterações';"
`$lines[849] = "    if (btn) { btn.disabled = false; btn.textContent = '💾 Salvar Alterações'; }"
`$lines[854] = "  if (!confirm('Tem certeza que deseja excluir esta escola? Esta ação não pode ser desfeita.')) return;"
`$lines[861] = "    toast('Escola excluída com sucesso!', 'success');"
`$lines[913] = "    if (typeof toast === 'function') toast('Escola não encontrada para edição', 'error');"
`$lines[945] = "    h += '<h2>Relatório de Escolas - SEDUC/RO (CAM)</h2>';"
`$lines[956] = "    h += '<th class=`"num`">Nº</th>';"
`$lines[957] = "    h += '<th>Competência</th>';"
`$lines[959] = "    h += '<th>Município</th>';"
`$lines[961] = "    h += '<th class=`"center`">Localização</th>';"
`$lines[963] = "    h += '<th class=`"right`">Matrículas</th>';"
`$lines[1012] = "    alert('Erro ao gerar relatório: ' + err.message);"
`$lines | Set-Content -Path .\js\escolas.js -Encoding UTF8
"@
$script | Out-File -FilePath .\fix_syntax_bom.ps1 -Encoding UTF8
powershell -ExecutionPolicy Bypass -File .\fix_syntax_bom.ps1
